CHROME_DRIVER = 'C:\\Python37\\chromedriver.exe'
FIREFOX_DRIVER = r'C:\\Python37\\geckodriver.exe'
OPEN_CHROME_DRIVER = False

ITERATOR = 50

MIN_SLEEP_TIME_MIN = 30
MAX_SLEEP_TIME_MIN = 40
SLEEP_TIME_QUICK_SEG = 60

IS_LIVE = False
LIVE_URL_VIDEO = 'https://www.youtube.com/watch?v=qeKK6LAhlIo'
LIVE_ITERATOR = 100
LIVE_MIN_SLEEP_TIME_MIN = 6
LIVE_MAX_SLEEP_TIME_MIN = 13
